### ISSUE TITLE
Data submission payload check against sample registration 

### ISSUE THREAD

**Issue by edsu7** [icgc-argo-workflows/data-processing-utility-tools#161]
This is to cover the scenario where sample registration details not matching data submission details.

A few considerations
- Will need use of API end point to pull sample registration details (https://clinical.platform.icgc-argo.org/)
  - blocked b/c needs ego token/authentication to run query.
  - good news is API end point is public
- Will need user to provide ARGO `donorID`, otherwise no easy way of parsing for `donorID` using `submitter_donor_Id`

**Comment by b-f-chan** [comment]
@edsu7 please revise scope and details of this ticket

**Comment by b-f-chan** [comment]
@edsu7 please revise scope and details of this ticket

**Comment by b-f-chan** [comment]
This has been implemented and PR ready for review --> But one scenario not being checked currently: When you submit a tumour, don't check if normal is registered (if you put any string for normal it will be accepted) --> Since we're moving this out of schema do we still need this check?

Answer: NO, don't need this check if matched normal being remove from schema

**Comment by b-f-chan** [comment]
Closing, done!
